apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: shell-demo-data
          mountPath: /usr/share/nginx/html

  volumes:
    - name: shell-demo-data
      emptyDir:
        { }
  hostNetwork: true
  dnsPolicy: Default

# apt-get update
# apt-get install -y tcpdump
# apt-get install -y lsof
# lsof
# apt-get install -y procps
# ps aux |grep nginx
# echo 'hello shell demo ' > /usr/share/nginx/html/index.html
# apt-get install -y curl
# curl localhost
# apt-get install -y iputils-ping
# ping 10.244.0.5
# apt-get install -y net-tools
# ifconfig
# apt-get install -y dnsutils
#