apiVersion: v1
kind: Service
metadata:
  name: nginx-web-statefulset-clu
  namespace: default
  labels:
    app: nginx-web-statefulset-clu
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
#      nodePort: 30001
  selector:
    app: nginx-web-statefulset-clu

# curl nodeip:30001
# kubectl exec -i -t dnsutils -- nslookup nginx-web-statefulset.default
