apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-web-statefulset
  namespace: default
  labels:
    app: nginx-web-statefulset
spec:
  serviceName: nginx-web-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-statefulset
  template:
    metadata:
      name: nginx-web-statefulset
      labels:
        app: nginx-web-statefulset
    spec:
      containers:
        - name: nginx-web-statefulset
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-web-statefulset
      # pvc pv-default already create
      volumes:
        - name: nginx-web-statefulset
          persistentVolumeClaim:
            claimName: pvc-default
# create pvc in pod template
#  volumeClaimTemplates:
#    - metadata:
#        name: nginx-web-statefulset
#        namespace: default
#      spec:
#        storageClassName: local-storage
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
