apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-default
  namespace: default
spec:
  storageClassName: local-storage
  volumeName: pv-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi