apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-deployment
  labels:
    app: bootcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootcamp
  template:
      metadata:
        labels:
          app: bootcamp
      spec:
        containers:
          - name: bootcamp
            image: jocatalin/kubernetes-bootcamp:v2
