apiVersion: v1
kind: Service
metadata:
  name: bootcamp-service
  labels:
    app: bootcamp
spec:
  selector:
    app: bootcamp
  ports:
    - name: bootcamp
      protocol: TCP
      port: 8080
      nodePort: 32601
      targetPort: 8080
  type: NodePort